plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.umar.yaraan.chate'
    compileSdk 35

    defaultConfig {
        applicationId "com.umar.yaraan.chate"
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName "1.0.5"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Use debug signing config so release bundle compiles and runs perfectly out of the box
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
