plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
}

android {
    namespace 'com.umar.yaraan.chate'
    compileSdk 35

    defaultConfig {
        applicationId "com.umar.yaraan"
        minSdk 24
        targetSdk 35
        versionCode 7
        versionName "1.0.7"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Use debug signing config so release bundle compiles and runs perfectly out of the box
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    // Firebase & Play Services Auth
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.auth
    implementation libs.play.services.auth

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
