plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.umar.yaraan.chate'
    compileSdk 35

    defaultConfig {
        applicationId "com.umar.yaraan.chate"
        minSdk 24
        targetSdk 35
        versionCode 10
        versionName "1.0.7"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Use debug signing config so release bundle compiles and runs perfectly out of the box
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

tasks.register("copyRootAssets", Copy) {
    from "../assets"
    into "src/main/assets"
    include "**/*"
}

project.afterEvaluate {
    tasks.named("preBuild").configure {
        dependsOn("copyRootAssets")
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation 'com.google.android.gms:play-services-auth:20.7.0'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
